#!/bin/sh
echo "This script checks if commands for Java, Node.js, yarn and serve are available. If they are not, we will try to install them for you."
echo " "

# Check if Java is installed
if [ -z "$(command -v java)" ]; then
  if [ "$(command -v apt-get)" ]; then
    # Install default Java jdk
    sudo apt-get update
    sudo apt-get install default-jdk
  else
    echo "Java not found"
    echo "Please install Java >= 11 manually and rerun the script!"
    exit 1
  fi
else
  echo "Java found on your system"
fi

if [ "$(command -v node)" ] && [ "$(command -v npm)" ]; then
  echo 'Node.js and npm found on your system'
elif [ "$(command -v apt-get)" ]; then
  # Debian / Ubuntu
  sudo apt-get update
  sudo apt-get install nodejs npm
elif [ "$(command -v yum)" ]; then
  # RHEL / CentOS / Fedora / IBM i
  yum install curl
elif [ "$(command -v dnf)" ]; then
  # RHEL / CentOS / Fedora
  dnf module install nodejs:12
elif [ "$(command -v pkg)" ]; then
  # FreeBSD/Android
  pkg install node
elif [ "$(command -v zypper)" ]; then
  # OpenSUSE
  zypper install nodejs12
elif [ "$(command -v pacman)" ]; then
  # ArchLinux
  pacman -S nodejs npm
elif [ "$(command -v emerge)" ]; then
  # Gentoo
  emerge nodejs
elif [ "$(command -v brew)" ]; then
  # MacOs
  brew install node
elif [ "$(command -v port)" ]; then
  # MacOs
  port install nodejs12
elif [ "$(command -v pkgin)" ]; then
  # MacOs / NetBSD / SmartOS and illumos
  pkgin -y install nodejs
elif [ "$(command -v pkg_add)" ]; then
  # OpenBSD
  pkg_add node
elif [ "$(command -v eopkg)" ]; then
  # Solus
  sudo eopkg install nodejs
elif [ "$(command -v xbps-install)" ]; then
  # Void Linux
  xbps-install -Sy nodejs
elif [ "$(command -v scoop)" ]; then
  # Scoop
  scoop install nodejs
elif [ "$(command -v cinst)" ]; then
  # cinst
  cinst nodejs.install
else
  echo 'Could not find a suitable package manager.'
  echo 'Please install everything manually!'
  exit 1
fi

# Check if yarn is installed
if [ "$(command -v yarn)" ]; then
  echo 'yarn found on your system'
elif [ "$(command -v npm)" ]; then
  # Install yarn via npm
  sudo npm install --global yarn
else
  echo 'Could not find npm package manager.'
  echo 'Please install yarn and serve manually!'
  exit 1
fi

# Check if serve is installed
if [ "$(command -v serve)" ]; then
  echo 'serve found on your system'
elif [ "$(command -v npm)" ]; then
  # Install serve
  sudo npm install --global serve
else
  echo 'Could not find npm package manager.'
  echo 'Please install serve manually!'
  exit 1
fi
