#!/bin/sh
echo "This will install curl, NodeJS and yarn"
echo " "

# Check if java is installed
if [ -z "$(command -v java)" ]; then
    echo "Java not found"
    echo "Please install Java >= 11 manually!"
    exit 1
else
    echo "Java found on your system"
fi

# Check if curl is installed (default for non empty string is -n)
if [ "$(command -v curl)" ]; then
  echo "Curl found on your system"
elif [ "$(command -v apt-get)" ]; then
  # Install curl debian/ubuntu
  sudo apt-get update
  sudo apt-get install curl
elif [ "$(command -v yum)" ]; then
  # Install curl RHEL/CentOS/Fedora
  yum install curl
elif [ "$(command -v zypper)" ]; then
  # Install curl OpenSUSE
  zypper install curl
elif [ "$(command -v pacman)" ]; then
  # Install curl ArchLinux
  pacman -Sy curl
else
    echo 'Curl not found'
    echo 'Please install curl manually!'
    exit 1
fi

if [ "$(command -v node)" ]; then
  echo 'Node.js found on your system'
else
  # Install Node.JS via curl (Ubuntu v13.3.0)
  curl https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz > node.tar.xz
  sudo mkdir -p /usr/local/lib/nodejs
  sudo tar -xJvf node.tar.xz -C /usr/local/lib/nodejs
  rm node.tar.xz

  # Export node path
  export PATH=/usr/local/lib/nodejs/node-v12.14.1-linux-x64/bin:$PATH
  . ~/.profile
fi


if [ "$(command -v yarn)" ]; then
  echo 'yarn found on your system'
elif [ "$(command -v npm)" ]; then
  # Install yarn via npm
  npm install --global yarn
else
  # Install yarn via curl (Ubuntu v1.21.1)
  curl -o- -L https://yarnpkg.com/install.sh | bash
fi
