#!/bin/bash
echo Please wait while backend and frontend servers are starting

cd ./scripts || exit

# Check if a tmux session, or new terminal/tab can be opened
if [ "$(command -v tmux)" ]; then
  echo Trying to run servers in a new tmux session named tormap.
  tmux new-session -s 'tormap' \; \
    send-keys 'bash ./backend.sh' C-m \; \
    split-window -v \; \
    send-keys 'bash ./frontend.sh' C-m \;
elif [ "$(command -v gnome-terminal)" ]; then
  echo Running frontend in current and backend in new gnome-terminal tab.
  gnome-terminal --tab --title="TorMap backend" -- ./backend.sh
  ./frontend.sh
elif [ "$(command -v xterm)" ]; then
  xterm -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v konsole)" ]; then
  konsole -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v terminator)" ]; then
  terminator -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v xfce4-terminal)" ]; then
  xfce4-terminal -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v tilda)" ]; then
  tilda -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v guake)" ]; then
  guake -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v yakuake)" ]; then
  yakuake -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v alacritty)" ]; then
  alacritty -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v urxvt)" ]; then
  urxvt -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v kitty)" ]; then
  kitty -e ./frontend.sh
  ./backend.sh
elif [ "$(command -v st)" ]; then
  st -e ./frontend.sh
  ./backend.sh
else
  ./frontend.sh &
  ./backend.sh
fi
