# Example Docker compose file for production deployment
version: '3.8'
name: tormap
services:
    backend:
        image: tormap/backend:${TORMAP_VERSION:-2}
        volumes:
            - ./tormap-data:/tormap-data
        depends_on:
            - database
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
        ports:
            - "8080:8080"

    database:
        image: postgres:14-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"

    frontend:
        image: tormap/frontend:${TORMAP_VERSION:-2}
        ports:
            - "80:80"
