app:
    http:
        cache:
            public:
                max-age-seconds: 0
    security:
        cors:
            allowed-origins: http://localhost:3000
descriptor:
    apiBaseURL: https://collector.torproject.org
    localDownloadDirectory: tormap-data/descriptors
    archiveRelayConsensuses: /archive/relay-descriptors/consensuses/
    archiveRelayServers: /archive/relay-descriptors/server-descriptors/
    recentRelayConsensuses: /recent/relay-descriptors/consensuses/
    recentRelayServers: /recent/relay-descriptors/server-descriptors/
ip-lookup:
    shouldCache: true
    locationDatabaseFile: /ip-lookup/location.mmdb
    autonomousSystemDatabaseFile: /ip-lookup/autonomous-system.mmdb
management:
    endpoints:
        enabled-by-default: false
        jmx:
            exposure:
                include: []
        web:
            # Actuator endpoints that are enabled individually from the endpoint config, will be exposed via web, if appearing in this list:
            exposure:
                include: health,info,metrics,caches,httptrace,flyway,logfile,mappings,scheduledtasks,threaddump
            base-path: /actuator
    endpoint:
        health:
            enabled: true
            show-details: when_authorized
        info:
            enabled: true
        metrics:
            enabled: true
        caches:
            enabled: true
        httptrace:
            enabled: true
        flyway:
            enabled: true
        logfile:
            enabled: true
            external-file: logs/spring-boot-logger.log
        mappings:
            enabled: true
        scheduledtasks:
            enabled: true
        threaddump:
            enabled: true
logging:
    file:
        path: logs/spring-boot-logger.log
server:
    port: 8080
    http2:
        enabled: true
    compression:
        enabled: true
        min-response-size: 1024
    tomcat:
        max-http-form-post-size: 1048576 # 1 MiB
        max-swallow-size: 1048576       # 1 MiB
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    flyway:
        baselineOnMigrate: true
        locations: classpath:database/migration
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                jdbc:
                    batch_size: 30
                    order_inserts: true
                    batch_versioned_data: true
                order_updates: true
    output:
        ansi:
            enabled: ALWAYS
    security:
        user:
            name: admin
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 1MB
springdoc:
    api-docs:
        path: /openapi
        enabled: true
    swagger-ui:
        path: /swagger
        enabled: true
