descriptor:
    apiBaseURL: https://collector.torproject.org
    localDownloadDirectory: tormap-data/descriptors
    archiveRelayConsensuses: /archive/relay-descriptors/consensuses/
    archiveRelayServers: /archive/relay-descriptors/server-descriptors/
    recentRelayConsensuses: /recent/relay-descriptors/consensuses/
    recentRelayServers: /recent/relay-descriptors/server-descriptors/
ip-lookup:
    shouldCache: true
    locationDatabaseFile: /ip-lookup/location.mmdb
    autonomousSystemDatabaseFile: /ip-lookup/autonomous-system.mmdb
management:
    endpoint:
        health:
            show-details: when_authorized
        logfile:
            external-file: logs/spring-boot-logger.log
    endpoints:
        jmx:
            exposure:
                include:
        web:
            exposure:
                include: health,info,metrics,caches,httptrace,flyway,logfile,mappings,scheduledtasks,threaddump,heapdump
            base-path: /actuator
logging:
    file:
        path: logs/spring-boot-logger.log
server:
    port: 8080
    http2:
        enabled: true
    compression:
        enabled: true
        min-response-size: 1024
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    flyway:
        baselineOnMigrate: true
        locations: classpath:database/migration
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                jdbc:
                    batch_size: 30
                    order_inserts: true
                    batch_versioned_data: true
                order_updates: true
    output:
        ansi:
            enabled: ALWAYS
    security:
        user:
            name: admin
            passwordFile: tormap-data/admin-password.txt
springdoc:
    api-docs:
        path: /openapi
    swagger-ui:
        path: /
