descriptor:
    apiBaseURL: https://collector.torproject.org
    localDownloadDirectory: resources/descriptors
    archiveRelayConsensuses: /archive/relay-descriptors/consensuses/
    archiveRelayServers: /archive/relay-descriptors/server-descriptors/
    recentRelayConsensuses: /recent/relay-descriptors/consensuses/
    recentRelayServers: /recent/relay-descriptors/server-descriptors/
database:
    defaultSequenceName: HIBERNATE_SEQUENCE
    ip2locationDatabaseFile: ip2location/IP2LOCATION-LITE-DB5.BIN
    shouldCacheIPLookup: true
scheduler:
    archiveRelayConsensuses: PT12H
    archiveRelayServers: PT12H
    recentRelayConsensuses: PT1H
    recentRelayServers: PT1H
    updateNodeAutonomousSystems: PT12H
    updateNodeFamilies: PT12H
    shouldOverwriteFamilies: false
server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:./resources/database/tormap;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=5;LOCK_TIMEOUT=30000
        username: sa
        password: ''
    flyway:
        baselineOnMigrate: true
        locations: classpath:database/migration
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.tormap.database.CustomH2Dialect
        hibernate:
            ddl-auto: validate
        open-in-view: false
    output:
        ansi:
            enabled: ALWAYS
springdoc:
    api-docs:
        path: /openapi
    swagger-ui:
        path: /

---

spring:
    h2:
        console:
            enabled: false
    config:
        activate:
            on-profile: prod
