descriptor:
    apiBaseURL: https://collector.torproject.org
    localDownloadDirectory: tormap-data/descriptors
    archiveRelayConsensuses: /archive/relay-descriptors/consensuses/
    archiveRelayServers: /archive/relay-descriptors/server-descriptors/
    recentRelayConsensuses: /recent/relay-descriptors/consensuses/
    recentRelayServers: /recent/relay-descriptors/server-descriptors/
ip-lookup:
    shouldCache: true
    locationLookup:
        dbipDatabaseFile: https://download.db-ip.com/free/dbip-city-lite-2023-03.mmdb.gz
    autonomousSystemLookup:
        maxmindDatabaseFile: https://download.db-ip.com/free/dbip-asn-lite-2023-03.mmdb.gz
management:
    endpoint:
        health:
            show-details: when_authorized
    endpoints:
        jmx:
            exposure:
                include:
        web:
            exposure:
                include: health,info,metrics,caches,httptrace,flyway,logfile,mappings,scheduledtasks,threaddump,heapdump
            base-path: /actuator
    httpexchanges:
        recording:
            include: PRINCIPAL,REMOTE_ADDRESS,REQUEST_HEADERS,RESPONSE_HEADERS,SESSION_ID,TIME_TAKEN
            maxInMemory: 100
logging:
    level:
        nl.basjes: warn
schedule:
    shouldOverwriteFamilies: false
    rate:
        recentRelayConsensuses: PT1H
        recentRelayServers: PT1H
        archiveRelayConsensuses: PT12H
        archiveRelayServers: PT12H
        updateRelayAutonomousSystems: PT12H
        updateRelayFamilies: PT12H
server:
    port: 8080
    compression:
        enabled: true
        min-response-size: 1024
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    flyway:
        locations: classpath:/db/migration
    output:
        ansi:
            enabled: always
    security:
        user:
            name: admin
            passwordFile: tormap-data/admin-password.txt
    web:
        resources:
            static-locations: classpath:/static
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui
