descriptor:
    apiBaseURL: https://collector.torproject.org
    localDownloadDirectory: resources/descriptors
    archiveRelayConsensuses: /archive/relay-descriptors/consensuses/
    archiveRelayServers: /archive/relay-descriptors/server-descriptors/
    recentRelayConsensuses: /recent/relay-descriptors/consensuses/
    recentRelayServers: /recent/relay-descriptors/server-descriptors/
ip-lookup:
    shouldCache: true
    locationLookup:
        dbipDatabaseFile: ip-lookup/location/dbip/dbip-city-lite.mmdb
    autonomousSystemLookup:
        maxmindDatabaseFile: ip-lookup/autonomous-system/maxmind/GeoLite2-ASN.mmdb
management:
    endpoint:
        logfile:
            external-file: logs/spring-boot-logger.log
    endpoints:
        jmx:
            exposure:
                include:
        web:
            exposure:
                include: health,info,caches,httptrace,flyway,logfile,mappings,scheduledtasks,threaddump,heapdump
            base-path: /actuator
    trace:
        http:
            include: PRINCIPAL,REMOTE_ADDRESS,REQUEST_HEADERS,RESPONSE_HEADERS,SESSION_ID,TIME_TAKEN
            maxInMemory: 100
logging:
    file:
        path: logs/spring-boot-logger.log
schedule:
    shouldOverwriteFamilies: false
    rate:
        archiveRelayConsensuses: PT12H
        archiveRelayServers: PT12H
        recentRelayConsensuses: PT1H
        recentRelayServers: PT1H
        updateNodeAutonomousSystems: PT12H
        updateNodeFamilies: PT12H
server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:./resources/database/tormap;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=5;LOCK_TIMEOUT=30000
        username: sa
        password: ''
    flyway:
        baselineOnMigrate: true
        locations: classpath:database/migration
    h2:
        defaultSequenceName: HIBERNATE_SEQUENCE
        console:
            enabled: true
            path: /h2
            settings:
                web-allow-others: true
    jpa:
        database-platform: org.tormap.database.CustomH2Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false
    output:
        ansi:
            enabled: ALWAYS
    security:
        user:
            name: admin
            passwordFile: resources/admin-password.txt
springdoc:
    api-docs:
        path: /openapi
    swagger-ui:
        path: /
