name: backend-docker-push

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend*'
    tags:
      - 'v*'

jobs:
  backend-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tormap/backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to DockerHub
        run: |
          cd backend
          ./gradlew bootBuildImage
          docker push tormap/backend

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
