name: backend

on:
  [push, pull_request]:
    paths:
      - 'backend/**'
      - '.github/workflows/backend*'

jobs:
  gradle_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: gradle/gradle-build-action@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Build and test
        run: ./gradlew test
