name: Build and deploy docker image

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy-docker.yml'

jobs:
  docker:
    name: Build and deploy docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: cd backend && ./gradlew bootBuildImage

      - name: Push image to DockerHub
        run: docker push juliushenke/tormap:latest
