name: Build and deploy to Firebase hosting for tormap.org

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy-prod.yml'

jobs:
  build-and-deploy:
    name: Build and deploy production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cd frontend && yarn && yarn build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
