name: frontend_build_deploy

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend*'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: yarn build
        run: |
          cd frontend
          yarn install --immutable
          yarn build

      - name: Deploy to preview channel
        if: github.event_name == 'pull_request' && (github.ref_name == 'master' || github.ref_name == 'main' || github.ref_name == 'development' || github.ref_name == 'dev')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Deploy to dev.tormap.org
        if: github.event_name == 'push' && (github.ref_name == 'development' || github.ref_name == 'dev')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_DEV }}'
          projectId: tormap-dev
          entryPoint: ./frontend
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Deploy to live tormap.org
        if: github.event_name == 'push' && (github.ref_name == 'master' || github.ref_name == 'main')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
