name: frontend-pull-request

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pull-request.yml'

jobs:
  frontend-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check yarn cache and build
        run: | 
          cd frontend
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: Deploy preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

