name: Frontend Pull Request

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: yarn build
        run: |
          cd frontend
          yarn install --immutable
          yarn build

      - name: Deploy to preview channel
        if: github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
