name: frontend_pull_request

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pull-request.yml'

jobs:
  frontend_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yarn build
        run: | 
          cd frontend
          yarn install --immutable
          yarn build

      - name: Deploy preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

