name: Frontend Build (reusable)

on:
  workflow_call:  # makes this callable from other workflows

jobs:
  frontend_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: yarn build
        run: |
          cd frontend
          yarn install --immutable
          yarn build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: frontend-build
          path: frontend/build
          if-no-files-found: error
          retention-days: 1
