name: frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and check yarn cache
        if: github.event_name == 'pull_request'
        run: |
          cd frontend
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: Build without checking yarn cache
        if: github.event_name != 'pull_request'
        run: |
          cd frontend
          yarn install --immutable --immutable-cache
          yarn build

      - name: Deploy preview channel
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Deploy live channel
        if: github.ref_name == 'master' || github.ref_name == 'main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORMAP_36F44 }}'
          projectId: tormap-36f44
          entryPoint: ./frontend
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

